include: package:lint/analysis_options.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude: [test/*.mocks.dart]

  errors:
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
